name = "reptracker"
main = "dist/worker.js"
compatibility_date = "2025-06-30"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
preview_urls = false

[[routes]]
pattern = "reptracker.amurpo.icu"
zone_name = "amurpo.icu"
custom_domain = true

[assets]
directory = "dist"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "reptracker-db"
database_id = "fbab730b-aaff-4bd2-99f6-5ec7eb36a418"

[[kv_namespaces]]
binding = "AVATARS"
id = "12c4e27cab4a49f0956d6a1158832233"

[[kv_namespaces]]
binding = "EXERCISE_IMAGES"
id = "aae86d589c3a4d7db627834d5b0f10fd"
preview_id = "9062031d0a124b339ce84e3740755189"

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[[queues.producers]]
binding = "EMAIL_QUEUE"
queue = "reptracker-email-queue"

[[queues.consumers]]
queue = "reptracker-email-queue"
max_batch_size = 10
max_batch_timeout = 5
max_retries = 3

[build]
command = "npm install && npm run build && npm run build:worker"
