name = "reptracker"
main = "dist/worker.js"
compatibility_date = "2025-06-30"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
preview_urls = false

[[routes]]
pattern = "reptracker.amurpo.icu"
zone_name = "amurpo.icu"
custom_domain = true

[assets]
directory = "dist"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "reptracker-db"
database_id = "fbab730b-aaff-4bd2-99f6-5ec7eb36a418"

[build]
command = "npm install && npm run build && npm run build:worker"
